# local:http://localhost:81/docs/swagger?url=http://localhost:81/docs/swagger.yml
# remote:https://dxcchina.github.io/pms/swagger?url=https://dxcchina.github.io/pms/swagger.yml
swagger: "2.0"

info:
  title: "pms api"
  version: "1.0"
basePath: "/api"
paths:
# @author: Wang Jianhui
  /project/{project_id}/users:
    get:
      summary: 查询项目成员
      operationId: controller.activity.project_user
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
# @author: Gao Le

  /project/name/{project_name}:
    get:
      summary: 查找项目名称
      operationId: controller.info.find_one_project_by_name
      parameters:
        - name: project_name
          in: path
          required: true
          type: string
      responses:
        200:
          description: ok
  /task:
    get:
      summary: api
      operationId: controller.info.task_list
      responses:
        200:
          description: ok
# @author: Wang Qianxiang
  /userlist:
    get:
      summary: api
      operationId: controller.project.user_list
      responses:
        200:
          description: ok
    post:
      summary: 更新项目成员
      operationId: controller.project.project_user_update
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
# @author: Xing Dong
  /task/list:
    get:
      summary: api
      operationId: controller.task.task_list
      responses:
        200:
          description: ok
  /demand/task:
    post:
      summary: api
      operationId: controller.task.task_add
      responses:
        200:
          description: ok
  /member/{projectId}:
    get:
      summary: api
      operationId: controller.task.getMemberInfo
      parameters:
        - name: projectId
          in: path
          required: true
          type: number
      responses:
        200:
          description: ok
  /demand/task/update:
    put:
      summary: api
      operationId: controller.task.update_task
      responses:
        200:
          description: ok
  /demand/{demand_id}/task/{task_id}:
    get:
      summary: api
      operationId: controller.task.task_info
      parameters:
        - name: demand_id
          in: path
          required: true
          type: number
        - name: task_id
          in: path
          required: true
          type: number
      responses:
        200:
          description: ok
    put:
      summary: api
      operationId: controller.task.task_update
      parameters:
        - name: demand_id
          in: path
          required: true
          type: number
        - name: task_id
          in: path
          required: true
          type: number
      responses:
        200:
          description: ok
# @author: Wang Qianxiang
# @author: Wang Qianxiang