swagger: "2.0"

info:
  title: "pms api"
  version: "1.0"
basePath: "/api"
paths:
# @author: Wang Jianhui
  /project/{project_id}/users:
    get:
      summary: 查询项目成员
      operationId: controller.activity.project_user
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
  /demand:
    get:
      summary: 查询需求
      operationId: controller.activity.demand_search
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: title
          in: query
          required: true
          type: string
        - name: projectId
          in: query
          required: true
          type: integer
      responses:
        200:
          description: ok
  /activity:
    post:
      summary: 创建活动
      operationId: controller.activity.activity_add
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - name: activity
          in: body
          description: user to add to the system
          required: true
          schema:
            $ref: '#/definitions/Activity'
      responses:
        200:
          description: 活动创建成功
  /login:
    post:
      summary: api
      operationId: controller.user.login
      responses:
        200:
          description: ok
  /user:
    post:
      summary: api
      operationId: controller.user.reg
      responses:
        200:
          description: ok
    get:
      summary: api
      operationId: controller.user.user_info
      responses:
        200:
          description: ok
    put:
      summary: api
      operationId: controller.user.user_update
      responses:
        200:
          description: ok
  /password:
    put:
      summary: api
      operationId: controller.user.change_password
      responses:
        200:
          description: ok
  /logout:
    get:
      summary: api
      operationId: controller.user.logout
      responses:
        200:
          description: ok
# @author: Gao Le
  /project:
    get:
      summary: 获取项目列表
      operationId: controller.info.project_list
      responses:
        200:
          description: ok
    post:
      summary: 创建项目
      operationId: controller.info.project_add
      responses:
        200:
          description: ok

  /project/name/{project_name}:
    get:
      summary: 查找项目名称
      operationId: controller.info.find_one_project_by_name
      parameters:
        - name: project_name
          in: path
          required: true
          type: string
      responses:
        200:
          description: ok
  /task:
    get:
      summary: api
      operationId: controller.info.task_list
      responses:
        200:
          description: ok
# @author: Wang Qianxiang
  /project/{project_id}:
    get:
      summary: api
      operationId: controller.project.project_info
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
    put:
      summary: 项目信息更新
      operationId: controller.project.project_update
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
  /userlist:
    get:
      summary: api
      operationId: controller.project.user_list
      responses:
        200:
          description: ok
  /project/{project_id}/user:
    get:
      summary: 查询项目成员
      operationId: controller.project.project_user
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
    post:
      summary: 更新项目成员
      operationId: controller.project.project_user_update
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
# @author: Xing Dong
  /project/demand:
    post:
      summary: api
      operationId: controller.demand.demand_add
      responses:
        200:
          description: ok
  /project/demand/detail/{demand_id}:
    get:
      summary: api
      operationId: controller.demand.demand_info
      parameters:
        - name: demand_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
  /project/demand/update:
    put:
      summary: api
      operationId: controller.demand.demand_update
      responses:
        200:
          description: ok
  /demand/{demand_title}:
    get:
      summary: api
      operationId: controller.task.demand_search
      parameters:
        - name: demand_title
          in: path
          required: true
          type: string
      responses:
        200:
          description: ok
  /demand/list:
    get:
      summary: api
      operationId: controller.task.demand_lists
      responses:
        200:
          description: ok
  /project/demand/{title}:
    get:
      summary: api
      operationId: controller.demand.find_demand_list_match_str

      parameters:
        - name: title
          in: path
          required: true
          type: string
      responses:
        200:
          description: ok
  /task/list:
    get:
      summary: api
      operationId: controller.task.task_list
      responses:
        200:
          description: ok
  /demand/task:
    post:
      summary: api
      operationId: controller.task.task_add
      responses:
        200:
          description: ok
  /member/{projectId}:
    get:
      summary: api
      operationId: controller.task.getMemberInfo
      parameters:
        - name: projectId
          in: path
          required: true
          type: number
      responses:
        200:
          description: ok
  /demand/task/update:
    put:
      summary: api
      operationId: controller.task.update_task
      responses:
        200:
          description: ok
  /demand/{demand_id}/task/{task_id}:
    get:
      summary: api
      operationId: controller.task.task_info
      parameters:
        - name: demand_id
          in: path
          required: true
          type: number
        - name: task_id
          in: path
          required: true
          type: number
      responses:
        200:
          description: ok
    put:
      summary: api
      operationId: controller.task.task_update
      parameters:
        - name: demand_id
          in: path
          required: true
          type: number
        - name: task_id
          in: path
          required: true
          type: number
      responses:
        200:
          description: ok
  /project/case:
    post:
      summary: api
      operationId: controller.case.case_add
      responses:
        200:
          description: ok
    put:
      summary: api
      operationId: controller.case.case_update
      responses:
        200:
          description: ok
  /project/case/detail/{case_id}:
    get:
      summary: api
      operationId: controller.case.case_detail
      parameters:
        - name: case_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
# @author: Wang Qianxiang
  /dashboard/{project_id}/demand:
    get:
      summary: 获取项目需求
      operationId: controller.dashboard.project_demand
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
  /dashboard/{project_id}/activity:
    get:
      summary: 获取项目活动
      operationId: controller.dashboard.project_activity
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
  /dashboard/{project_id}/testCase:
    get:
      summary: 获取项目测试案例
      operationId: controller.dashboard.project_test_case
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
  /dashboard/{project_id}/testResult:
    get:
      summary: 获取项目测试结果
      operationId: controller.dashboard.project_test_result
      parameters:
        - name: project_id
          in: path
          required: true
          type: integer
      responses:
        200:
          description: ok
definitions:
  Activity:
    type: object
    properties:
      title:
        type: string
      projectId:
        type: integer
      demand:
        type: array
        items:
          type: integer
    required:
    - title
    - projectId
    - demand
