swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

paths:
  /user:
    post:
      summary: Generate greeting
      operationId: controller.user.reg
      responses:
        200:
          description: greeting response
  /login:
    post:
      summary: Generate greeting
      operationId: controller.user.login
      responses:
        200:
          description: greeting response
  /user:
    get:
      summary: Generate greeting
      operationId: controller.user.user_info
      responses:
        200:
          description: greeting response
  /user:
    get:
      summary: Generate greeting
      operationId: controller.user.user_info
      responses:
        200:
          description: greeting response
